### ISSUE TITLE
Possible mummer issue during hasm.sh

### ISSUE THREAD

**Issue by peterdfields** [PacificBiosciences/FALCON_unzip#34] opened 2016-08-23 11:30 UTC
A number of errors seem to be arising related to mummer during the hasm.sh step. A gist of the log can be found at:

https://gist.github.com/peterdfields/99a9903350e6376f553791457eb8c379

**Comment by pb-jchin** [comment] 2016-08-24 00:38
yes. this is some an un-solved problem. We use nucmer to reduce the duplicated sequences but sometimes there is actually no h-tig generated. In such case, the nucmer will throw out errors.  Ideally, we need to detect the where the h-tig is empty. This is certainly some time needed to be improved in the future.

**Comment by peterdfields** [comment] 2016-08-24 11:47
Yes, that makes sense. But can it be a case that these failed mummer jobs is causing the premature end of the fc_unzip.py run?

**Comment by lxliangit** [comment] 2016-10-04 07:58
Dear Jason Chin @pb-jchin and @peterdfields,

I also encountered the similar issue. In my case, the mummer issue has two sources:
1. h_ctg_all.$ctg_id.fa is totally empty
2. h_ctg_all.$ctg_id.fa has empty sequence (There is only a ">header" in the fasta file)

For the first source, I tried some simple patches by myself, in which I skip those empty fasta files, just like what the original code did to those non-exist (I wonder whether these is or not) fasta.

For the second source, I still cannot figure out the reason.

bless~
Xingliang

**Comment by jfass** [comment] 2016-10-04 21:52
I'll second this report (with the [ERROR]Contents of '...hasm.sh.log' ...). I'm on a 512G 48 cpu server:
**
$ uname -a
Linux ganesh 4.4.0-31-generic #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
**

I'm just running 'fc_unzip.py fc_unzip.cfg', with the config file as follows:
**
[General]
# the job_type is not used for now.
job_type=local
[Unzip]
input_fofn=input.fofn
input_bam_fofn=input_bam.fofn
smrt_bin=/home/jfass/tools/pitchfork/deployment/bin/temp
sge_phasing= -pe smp 12 -q bigmem
sge_quiver= -pe smp 24 -q bigmem
unzip_concurrent_jobs = 4
quiver_concurrent_jobs = 2
**

[out.txt](https://github.com/PacificBiosciences/FALCON_unzip/files/509578/out.txt)

**Comment by jfass** [comment] 2016-10-05 18:58
Hey @lxliangit, can you go into any detail on the patches you made, to cover those cases where h_ctg_all.[...].fa was empty? I'm seeing more than half of the indices in this state. I haven't seen any with only a header and no sequence.

For everyone, why are these occurring? Are they more prone to happen in highly uniform samples? I have a dataset that's pretty much haploid for maybe 99% of its length, but should have large variation in the remaining 1%. Are the contig indices generated from the a_ctg's? or from all over the genome?

**Comment by jfass** [comment] 2016-10-05 22:14
So, I think I was able to get past this problem unscathed. At first I edited the 'hasm.sh' script in the '1-hasm' directory (under '3-unzip'), but that script gets rewritten from code in 'unzip.py' in the virtual environment files ... specifically, I modified the 'task_hasm()' function in 'Python_venv/lib/python2.7/site-packages/falcon_unzip-0.1.0-py2.7.egg/falcon_unzip/' ... or rather the for loop in the bash code contained in it, from this:

'''
for f in `cat ../reads/ctg_list `;do cd $WD/$f; fc_dedup_h_tigs.py $f; done
'''
... to this:
'''
ls -la */h_ctg_all.*.fa | perl -ane 'print if $F[4]!=0' | cut -f2 -d\. | while read f; do cd $WD/$f; fc_dedup_h_tigs.py $f; done
'''

... So, it finds the h_ctg files that are completely empty (which worked for me, but would have to be modified for @lxliangit who has mentioned files with a fasta header but no sequence), and sends their id's to the dedup script. After making the modification I just ran 'fc_unzip.py fc_unzip.cfg' again from the main directory, and it walked through the non-empty directories and then finished up the unzip step soon after.

I'd like to emphasize that I'm just fumbling around. This allowed unzip to finish, but I'd really like to understand why about 2/3rds of my htigs are empty ... am I missing something?

**Comment by lxliangit** [comment] 2016-10-06 03:24
Hi @jfass and all,

My patch to this issue is very ad hoc. Just for the two sources I've mentioned:
1. h_ctg_all.$ctg_id.fa is totally empty
2. h_ctg_all.$ctg_id.fa has empty sequence (There is only a ">header" in the fasta file)

I changed the source code of dedup_h_tigs.py
```
    # if os.path.exists("h_ctg_all.{ctg_id}.fa".format(ctg_id = ctg_id)):
    #     os.system("nucmer -mum p_ctg.{ctg_id}.fa h_ctg_all.{ctg_id}.fa -p hp_aln".format(ctg_id = ctg_id))
    #     os.system("show-coords -T -H -l -c hp_aln.delta > hp_aln.coor")
    # else:
    #     sys.exit(0) #it is ok if there is no h_ctg_all.{ctg_id}.fa, don't want to interupt the workflow
    
    if os.path.exists("h_ctg_all.{ctg_id}.fa".format(ctg_id = ctg_id)):
        if os.stat("h_ctg_all.{ctg_id}.fa".format(ctg_id = ctg_id)).st_size > 0:

            # temporary patch for those fastas without sequence but only a header
            with open("h_ctg_all.{ctg_id}.fa".format(ctg_id = ctg_id)) as f:
                lines=f.readlines()
            if lines[1].rstrip('\n') == '':
                sys.exit(0)

            os.system("nucmer -mum p_ctg.{ctg_id}.fa h_ctg_all.{ctg_id}.fa -p hp_aln".format(ctg_id = ctg_id))
            os.system("show-coords -T -H -l -c hp_aln.delta > hp_aln.coor")
        else:
            sys.exit(0)
    else:
        sys.exit(0) #it is ok if there is no h_ctg_all.{ctg_id}.fa, don't want to interupt the workflow
```
After that, my FALCON_unzip can complete it's run.

**Comment by pb-cdunn** [comment] 2016-10-06 15:11
We'll definitely take the `stat` code. Good idea.

I don't yet understand this part:
```py
            # temporary patch for those fastas without sequence but only a header
            with open("h_ctg_all.{ctg_id}.fa".format(ctg_id = ctg_id)) as f:
                lines=f.readlines()
            if lines[1].rstrip('\n') == '':
                sys.exit(0)
```
If there is only a header, couldn't `len(lines) == 1`? In that case, `lines[1]` is an error. No? Maybe it was dumped with a blank extra line, but that might not always be the case.

Also, the file might be large. We do not need to read the entire file, just the first 1 or 2 lines. Agreed? If so, we might handle that differently. (That may be a premature optimization, but it's pretty easy.)

At any rate, the idea is a good one. Thanks for finding and solving this.

Jason, we should leave this open until we update the code.

**Comment by pb-jchin** [comment] 2016-10-06 16:09
@lxliangit @pb-cdunn Thanks.  For long team, I would like to replace nucmer so we can do alignment internally.  I think the patch is reasonable, we can do some quick tests and incorporate it to the codebase.

**Comment by lxliangit** [comment] 2016-10-07 00:09
Hi @pb-cdunn ,

Thank you for your suggestion! Yes, agree, the patch definitely should be more elegant. As I mentioned, it's just a ad hoc solution.

In my case, h_ctg_edges.$ctg_id and h_ctg_path.$ctg_id are all empty. Only h_ctg_all.$ctg_id.fa has a header and an empty $seq line. And such case is rare (only 1 actually) but reproducible. 

I am curious why this happens.

**Comment by pb-jchin** [comment] 2016-10-07 14:51
@lxliangit you can check what is going on by examining `3-unzip/0-phasing` and `3-unzip/1-hasm`.  If there is an previous step that does not work (due to computation or the nature of the genome),  then you can see what is going. For example, if there is not much variations to separate or the reads are not fetched properly, then you won't have the haplotigs generated.

**Comment by lxliangit** [comment] 2016-10-12 09:59
Hi @pb-jchin ,

Thank you for your reply.

I have checked the files in 0-phasing/ and 1-hasm/ for the suspicious empty sequence fasta, from the file sizes and directory structure, it looks similar to other normal fasta files.

I dig the source code of graphs_to_h_tigs.py using the suspicious contig. I found that the sub haplotype graph of it looks like this:

![sub_hg](https://cloud.githubusercontent.com/assets/4134380/19305625/5e7ceda6-90a4-11e6-9625-8f617961e386.png)

Therefore, when the following code did it's job:
```
 483                 sources = [n for n in sub_hg.nodes() if sub_hg.in_degree(n) != 1 ]
 484                 sinks = [n for n in sub_hg.nodes() if sub_hg.out_degree(n) != 1 ]
```
, there is one source and one sink which are same.

Then, when the following code ran:
```
 505                             path = nx.shortest_path(sub_hg, s, t, weight="score")
```
It will return the path with only one node (which is also the source and sink node as well) based on what [shortest_path is implemented to do](https://networkx.github.io/documentation/networkx-1.10/_modules/networkx/algorithms/shortest_paths/weighted.html#single_source_dijkstra). Then, I think the above code of line 505 doesn't do what it really wanted to do (find the shortest path).

What do you think?

**Comment by pb-jchin** [comment] 2016-10-12 16:12
I think the proper logic is when the source and the sink is the same, we need to inform the user there are loop (it could be real circular DNA or some repeat induce look.) When that happen, we need to use a new source nodes (e.g., from the offspring of the initial source node.) to avoid such "short-cut".

Theoretical, the correct path finding should include the number of overlapped base.  The general idea is that the more bases that are overlapped, there is more evidence the path is correctly reflecting the underlying genome.  On the other hand, there is no simple algorithm to find the maximum path when there is a loop. The shortest path strategy get most cases right but it might not be ideal for the case there are complicated repeats and when there are some non-trivial loops.

**Comment by lxliangit** [comment] 2016-10-13 05:39
@pb-jchin , thank you for your prompt reply. Currently, I am using a temporary work-around by checking whether the seq is empty before putting it's header in the h_ctg_all.$ctg_id.fasta.

Here is my change of original 570, 571 lines of graphs_to_h_tigs.py:
```python
if len(seq) != 0:
    print >> h_tig_fa, ">%s_%03d" % (ctg_id, h_tig_id)
    print >> h_tig_fa, "".join(seq)
    h_tig_id += 1
```

**Comment by danshu** [comment] 2016-11-15 14:02
@lxliangit  May I know whether your patch solved the problem or just let Falcon_unzip to finish? In my case I also have nucmer error messages but the 3-unzip step completed. I have error in the 4-quiver step and I don't know whether it is caused by this nucmer error.

**Comment by lxliangit** [comment] 2016-11-15 14:51
Hi @danshu 

If you indicate the "problem" of my previous report:
> 1. h_ctg_all.$ctg_id.fa is totally empty
> 2. h_ctg_all.$ctg_id.fa has empty sequence (There is only a ">header" in the fasta file)

No.

If you mean the problem of halt of FALCON_unzip because of above-mentioned two cases.

Yes. After that, FALCON_unzip can run successfully. However, if I remember correctly, 4-quiver also requires tuning but not related to this issue actually.

**Comment by danshu** [comment] 2016-11-15 14:54
@lxliangit Thanks for you reply.
May I know how did you tune 4-quiver to let it run successfully?
My "fc_quiver.py" step failed with the follwoing error message:
"001301F 9[E::hts_open_format] fail to open file '../4-quiver/reads/000011F_036.sam'
../track_reads_h.sh: line 13: 13711 Segmentation fault (core dumped) fc_select_reads_from_bam.py input_bam.fofn"

**Comment by ascendo** [comment] 2017-04-06 04:25
@danshu did you solve the problem? After this patch I was stuck in same step.

**Comment by danshu** [comment] 2017-04-06 04:33
@ascendo It seems the system limits the number of opened files. You may try after increasing this limit.

**Comment by ascendo** [comment] 2017-04-06 04:35
Thank you for a quick reply.

I check my system limit by "ulimit" and it shows unlimit.

Is there any specific way?
Thanks.

**Comment by danshu** [comment] 2017-04-06 04:41
@ascendo  You may check using "ulimit -a" and check "open files".

**Comment by ascendo** [comment] 2017-04-06 04:53
Oh thanks!

**Comment by pb-cdunn** [comment] 2017-04-11 04:26
Ah, I see the problem. In `falcon_unzip/select_reads_from_bam.py`, we use a dictionary of open files for each "ctg". We need to close and re-open those files as needed. We already do that elsewhere.

Hopefully we can get to that soon.

**Comment by pb-cdunn** [comment] 2017-04-20 20:46
This is now fixed in our private repo. Not sure when the fix will be public.

**Closed by pb-cdunn** 2017-04-20 20:46 UTC
Labels: bug

**Comment by peterdfields** [comment] 2017-04-20 21:21
Is it possible to leave the issue open until this version is released?

**Comment by olechnwin** [comment] 2018-07-11 15:08
@lxliangit, the two sources you mentioned above were also my problems. I tried to find dedup_h_tigs.pyc to modify but I can only find the .pyc. How to do this workaround so I can run falcon-unzip to completion?

**Comment by olechnwin** [comment] 2018-07-11 15:08
any update on this bug? How to fix this?

**Comment by pb-cdunn** [comment] 2018-08-05 23:03
I think this is fixed in the latest binary release.
