### ISSUE TITLE
unzip 1-hasm complains of missing edge

### ISSUE THREAD

**Issue by jasmynp** [PacificBiosciences/FALCON_unzip#92] opened 2017-09-18 22:09 UTC
I've encounter a data set where the 1-hasm stage of unzip is complaining of not seeing an edge.  I am not sure how to resolve this as I have run quite a few datasets and haven't come across this until now. 
```py
fc_phased_ovlp_to_graph.py preads.p_ovl --min_len 2500 > fc.log
+ fc_phased_ovlp_to_graph.py preads.p_ovl --min_len 2500
Traceback (most recent call last):
  File "/20170605/git/FALCON_unzip/bin/fc_phased_ovlp_to_graph.py", line 6, in <module>
    main(sys.argv)
  File "/20170605/git/FALCON_unzip/lib/python2.7/site-packages/falcon_unzip/phased_ovlp_to_graph.py", line 1383, in main
    ug2.remove_edge(s, t, key=v)
  File "/20170605/git/FALCON_unzip/lib/python2.7/site-packages/networkx/classes/multidigraph.py", line 395, in remove_edge
    "The edge %s-%s is not in the graph." % (u, v))
networkx.exception.NetworkXError: The edge 000570994:B-000571986:E is not in the graph.
```

**Comment by ctxchris** [comment] 2017-11-13 09:41
Hi,

same error here. Any idea how to fix that?

Thanks,
Chris

**Comment by ctxchris** [comment] 2017-11-15 08:59
I think the issue is connected with running the last stage of the assembly with different pread length cut offs. When I run Falcon unzip on the initial results obtained by the initial parameter setting it works. Running it on output from a different parameter setting it fails. To fix it, renamed 1-preads_ovl and 2-asm-falcon folders and run Falcon again with the chosen parameters. I observed the same issue for three independent assemblies. For a small genome that’s a feasible approach, but for bigger ones it requires substantial additional runtime. I assume it’s not necessary to delete the complete 1-preads_ovl folder though.

Thanks,
Chris

**Comment by pb-cdunn** [comment] 2018-02-09 23:32
@ctxchris, Could you provide an example of a parameter that change that causes this crash?

**Comment by pkuerten** [comment] 2018-02-23 05:47
Hi, I am getting the same error. I am using default parameters. The error is below.
```py
python -m falcon_unzip.mains.phased_ovlp_to_graph preads.p_ovl --min_len 2500 > fc.log
+ python -m falcon_unzip.mains.phased_ovlp_to_graph preads.p_ovl --min_len 2500
Traceback (most recent call last):
  File "/mnt/software/unstowable/anaconda/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/mnt/software/unstowable/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/scratch/cdunn/fork/.git/LOCAL4/lib/python2.7/site-packages/falcon_unzip/mains/phased_ovlp_to_graph.py", line 1538, in <module>
  File "/scratch/cdunn/fork/.git/LOCAL4/lib/python2.7/site-packages/falcon_unzip/mains/phased_ovlp_to_graph.py", line 1534, in main
  File "/scratch/cdunn/fork/.git/LOCAL4/lib/python2.7/site-packages/falcon_unzip/mains/phased_ovlp_to_graph.py", line 1339, in run
  File "<path>/FALCON-unzip/fc_env_171120/lib/python2.7/site-packages/networkx/classes/multidigraph.py", line 395, in remove_edge
    "The edge %s-%s is not in the graph." % (u, v))
networkx.exception.NetworkXError: The edge 002092058:E-012134678:B is not in the graph.
```
When I grep for the two numbers in

    ./3-unzip/1-hasm/rid-to-phase-all/rid_to_phase.all
which I think is the input to this function, I see
```
002092058 002255F 1 1
012134678 002255F 1 1
```
For multiple other datasets the code worked fine. Any guidance on how to resolve this would be most helpful. Thanks,

**Comment by ctxchris** [comment] 2018-02-23 07:48
The error occurs when it change `length_cutoff_pr`

**Comment by pkuerten** [comment] 2018-02-23 08:53
A correction on my earlier question, I am using length_cutoff_pr=5000 (not sure if it is default)

**Comment by pb-cdunn** [comment] 2018-02-26 17:05
I think the latest tarball has a fix for this. It will trap the error and continue. I *think* the error is harmless, but I have not actually been able to repro it yet myself.

**Comment by pkuerten** [comment] 2018-03-27 10:35
For me falcon_unzip stops with the error. Any suggestions on how to address this would be really helpful.

**Comment by pb-cdunn** [comment] 2018-04-03 20:59
Can you provide a small-ish test-case? If we can repro, we can fix, but for me, the error seems to be gone.

**Closed** 2018-06-21 23:16 UTC
