### ISSUE TITLE
Problem running unzip from conda on clusters 

### ISSUE THREAD

**Issue by Lcornet** [PacificBiosciences/FALCON_unzip#143] opened 2019-01-18 15:24 UTC
Dear Falcon team,

I have an error while running unzip on our cluster , seel below.

Can you help me ?

```py
falcon-unzip 1.1.4
falcon-kit 1.2.4
pypeflow 2.1.1
Traceback (most recent call last):
  File "/media/vol2/home/lcornet/anaconda2/envs/denovo_asm/bin/fc_unzip.py", line 11, in <module>
    load_entry_point('falcon-unzip==1.1.4', 'console_scripts', 'fc_unzip.py')()
  File "/media/vol2/home/lcornet/anaconda2/envs/denovo_asm/lib/python2.7/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/media/vol2/home/lcornet/anaconda2/envs/denovo_asm/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/media/vol2/home/lcornet/anaconda2/envs/denovo_asm/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/media/vol2/home/lcornet/anaconda2/envs/denovo_asm/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/media/vol2/home/lcornet/anaconda2/envs/denovo_asm/lib/python2.7/site-packages/falcon_unzip/mains/start_unzip.py", line 3, in <module>
    from .. import unzip
  File "/media/vol2/home/lcornet/anaconda2/envs/denovo_asm/lib/python2.7/site-packages/falcon_unzip/unzip.py", line 7, in <module>
    from .tasks import unzip as tasks_unzip
  File "/media/vol2/home/lcornet/anaconda2/envs/denovo_asm/lib/python2.7/site-packages/falcon_unzip/tasks/unzip.py", line 5, in <module>
    from .. import io
  File "/media/vol2/home/lcornet/anaconda2/envs/denovo_asm/lib/python2.7/site-packages/falcon_unzip/io.py", line 21, in <module>
    from pysam.libcalignmentfile import AlignmentFile#, AlignmentHeader
  File "/media/vol2/home/lcornet/anaconda2/envs/denovo_asm/lib/python2.7/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
```

**Comment by pb-cdunn** [comment] 2019-03-05 16:26
I think this relates to our openssl woes, a huge problem in Bioconda. Several Bioconda folks are currently working on it. (The problem is that openssl-1.0.2 and openssl-1.1.1 are not binary compatible.)

https://github.com/bioconda/bioconda-recipes/pull/13909

We'll soon rebuild pb-assembly to see whether this solves the problem. But I'll close this now because the same problem is reported elsewhere.

**Closed as completed by pb-cdunn** 2019-03-05 16:26 UTC
